const services = {
  pos: { title: 'Pós-graduação <em>ou MBA</em>', intro: 'Estruturamos seu curso ou mentoria como um projeto acadêmico consistente, apto a ser apresentado a instituições de ensino superior parceiras.', side: 'Eleve sua expertise a uma nova categoria.', copy: 'Da matriz curricular à documentação pedagógica, organizamos o seu conhecimento para aproximar o projeto de oportunidades na educação superior.', points: [['01','Credibilidade e posicionamento','Um projeto acadêmico bem estruturado eleva a percepção de valor e fortalece sua autoridade.'],['02','Expansão de mercado','Abra espaço para públicos que buscam formações de maior profundidade e reconhecimento.'],['03','Documentação pedagógica','Matriz, ementas, carga horária e referenciais organizados para análise de instituições parceiras.']] },
  extensao: { title: 'Extensão <em>universitária</em>', intro: 'Apoio na modelagem de cursos de menor carga horária, compatíveis com os requisitos e boas práticas educacionais aplicáveis.', side: 'Transforme conhecimento em credibilidade.', copy: 'Adaptamos seu conteúdo com clareza pedagógica e visão de mercado para torná-lo mais sólido e valorizado.', points: [['01','Maior valor percebido','Uma experiência educacional estruturada fortalece a confiança do aluno.'],['02','Novas oportunidades','Projetos bem modelados ampliam a conversa com parceiros e instituições.'],['03','Assessoria especializada','Orientação da estrutura do conteúdo até a documentação necessária.']] },
  metep: { title: 'Consultoria <em>METEP</em>', intro: 'Método Estratégico de Transformação e Performance para quem quer conduzir seu conhecimento como uma empresa de educação.', side: 'Estratégia para crescer com direção.', copy: 'O METEP traduz sua visão em oportunidades de produto, posicionamento, lançamentos e inovação contínua.', points: [['01','Visão estratégica','Leia seu infoproduto como negócio e defina uma rota sustentável de crescimento.'],['02','Oportunidades de mercado','Identifique nichos, diferenciais e extensões possíveis para a sua oferta.'],['03','Performance contínua','Crie ciclos de melhoria que mantêm seu negócio relevante e atrativo.']] },
  consultoria: { title: 'Consultoria <em>educacional</em>', intro: 'Estratégia personalizada para aprimorar qualidade, eficácia e rentabilidade de cursos, mentorias e outros produtos educacionais.', side: 'Mais clareza para decidir. Mais método para evoluir.', copy: 'Unimos experiência de aprendizagem, estratégia de produto e visão comercial para fazer sua oferta avançar.', points: [['01','Otimização de conteúdo','Aprimore organização, relevância e experiência de aprendizagem.'],['02','Lançamentos e vendas','Desenvolva uma estratégia de posicionamento, funil e precificação alinhada à oferta.'],['03','Melhoria contínua','Faça seu produto evoluir com o mercado e com as necessidades reais dos alunos.']] },
  cursos: { title: 'Cursos <em>rápidos</em>', intro: 'Capacitação objetiva para infoprodutores que querem superar desafios de estrutura, mercado e posicionamento.', side: 'Aprendizado prático para quem constrói educação.', copy: 'Conteúdos diretos, desenhados para apoiar decisões melhores no mercado de produtos digitais.', points: [['01','Aplicação imediata','Ferramentas e conhecimentos para colocar em prática no seu negócio.'],['02','Visão de mercado','Leitura atual das dores de quem vende, ensina e escala conhecimento.'],['03','Evolução profissional','Mais repertório para estruturar ofertas de valor e experiências melhores.']] }
};
const type = new URLSearchParams(window.location.search).get('tipo') || 'pos';
const service = services[type] || services.pos;
document.title = service.title.replace(/<[^>]+>/g, '') + ' — iSnap Labs';
document.getElementById('service-title').innerHTML = service.title;
document.getElementById('service-intro').textContent = service.intro;
document.getElementById('service-side-title').textContent = service.side;
document.getElementById('service-side-copy').textContent = service.copy;
document.getElementById('service-list').innerHTML = service.points.map(([number, title, copy]) => `<article><span>${number}</span><div><h3>${title}</h3><p>${copy}</p></div></article>`).join('');
